name = "rupert"
defaultTargets = ["Rupert"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.style.multiGoal = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.25.1"

[[require]]
name = "tryAtEachStep"
git = "https://github.com/dwrensha/tryAtEachStep"
rev = "lean-v4.25.0"

[[lean_lib]]
name = "Rupert"
